Henry-Proyecto-Firnal-P-10b/vite-front-PF

src/App.jsx, src/components/sign-in-form/sign-in-form.jsx, src/components/sign-up-form/sign-up-form.jsx, src/routes/authentication/authentication.jsx, src/routes/authentication/signUp.jsx
Reajuste el login, lo traduje todo al español, ahora muestra primero para ingresar y le da la opción de redigirirlo a una nueva ruta y componente para registrarse, una vez se registre lo redirige al inicio de sesión.
=> reajuste del loguin

src/app/store.js, src/components/card-item/card-item.jsx, src/components/card/card.jsx, src/components/cart-dropdown/cart-dropdown.jsx, src/components/cart-icon/cart-icon.jsx, src/main.jsx, src/routes/checkout/checkout.jsx
se agrego la funcionalidad del carrito para que no se borre al actualizar la pagina
=> funcionalidad de car persist

src/components/hero-section/hero.jsx
centre tambien Titulos: Productos Recomendados y Productos Imperdibles que no se veian bien
=> arreglando filtros productos imperdibles/recomendados

src/components/navigation/navigation.jsx, src/components/navigation/navigation.module.css, src/components/pagination/pagination.jsx, src/features/productsPagination/productsPaginationSlice.js
searchBar funcional, algunas modificaciones en pagination, creación de estado global de pagina para utilizar en el componente.
=> searchBar funcional

src/components/cart-dropdown/cart-dropdown.jsx, src/components/checkout-form/checkout-form.jsx, src/components/checkout-form/checkout-form.module.css, src/components/common/button/button.jsx, src/components/common/button/button.module.css, src/routes/cart/cart.jsx, src/routes/cart/cart.module.css, src/routes/checkout/checkout.jsx, src/routes/checkout/checkout.module.css
Sea la pagina y se establece el formulario es responsive
=> Checkout Page y form

src/components/navigation/navigation.jsx
Propiedad de navigate para cuando la busqueda se hace en home
=> ajuste redireccion al buscar cuando estas en home

src/components/panel-admin/create-product/create-product.jsx, src/utils/firebase/firebaseClient.js
Agregue propiedad active en el post de los productos
=> agregue propiedad active para la creación de productos

src/App.jsx, src/components/card/card.jsx, src/components/navigation/navigation.jsx, src/components/navigation/search.js, src/components/pagination/helper.js, src/components/pagination/pagination.jsx, src/components/products/products.jsx, src/features/products/productSlice.js, src/features/productsPagination/productsPaginationSlice.js, src/utils/firebase/firebaseClient.js
reestructurando paginacion y busqueda
=> reestructurando paginacion y busqueda

src/App.jsx, src/components/card/rating/rating-preview.jsx, src/components/cart-dropdown/cart-dropdown.jsx, src/components/checkout-item/checkout-item.module.css, src/components/detail-component/detail-component.jsx, src/components/detail-component/detail-component.module.css, src/components/filters-bar/filtersBar.jsx, src/components/filters/filters.jsx, src/components/filters/filters.module.css, src/components/filtersComponent/filtersComponent.jsx, src/components/footer/footer.jsx, src/components/navigation/navigation.jsx, src/components/no-review/no-review.jsx, src/components/products/products.jsx, src/components/products/products.module.css, src/components/review-component/review-component.jsx, src/components/review-component/review-component.module.css, src/components/sign-in-form/sign-in-form.jsx, src/components/sign-up-form/sign-up-form.jsx, src/helper/dateToTimeStamp.js, src/helper/timeStampToDate.js, src/routes/authentication/authentication.jsx, src/routes/authentication/signUp.jsx, src/routes/cart/cart.jsx, src/routes/cart/cart.module.css, src/routes/checkout/checkout.module.css
arreglando estilos de la pagina 
filtos,
carrito
=> arreglando estilos de la pagina 

package-lock.json, package.json, src/components/sign-up-form/sign-up-form.jsx
=> se agrego envio de email registro de usuarios

src/components/filters/filters.jsx, src/components/filters/slider.jsx, src/features/products/productSlice.js
se agrego ordenamiento por nombre, precio, rating, y se agrego el filtro de rango de precios
=> se agrego el ordenamiento y filtrado de rango por precio

src/components/filters/filters.jsx, src/components/filters/slider.jsx, src/features/products/productSlice.js
volviendo a subir el codigo de ordenamiento filtros
=> Ordenamiento

src/components/filters/filters.jsx, src/components/filters/filters.module.css
cambios nuevos en los filtros
Arreglando estilos
=> cambios nuevos en los filtros

src/components/filters/filters.jsx, src/components/filters/filters.module.css, src/components/products/products.jsx, src/features/userData/userDataSlice.js
=> Cambios en filtros

src/components/navigation/links-navbar/links-navbar.jsx, src/components/navigation/navigation.jsx
ahora solo el adm puede ingresar a amd
=> ahora solo el adm puede ingresar a amd

src/components/panel-admin/create-product/create-product.jsx
Lista las validaciones del create product
=> validacion en agregar producto listo

src/components/panel-admin/edit-product/edit-product.jsx, src/components/panel-admin/side-bar/side-bar.jsx
Ya se modifican los productos desde el Admin 
Falta darle estilos
=>  Modificar Productos desde Admin Funcionando

package-lock.json, src/components/payment-gateway/checkout-form/checkout-form.jsx
=> checkout validado

src/App.jsx, src/components/panel-admin/create-product/create-product.jsx, src/components/panel-admin/create-product/create-product.module.css, src/components/panel-admin/home-admin/home-admin.jsx, src/components/panel-admin/orders/ventasTotales.jsx, src/components/panel-admin/orders/ventasTotales.module.css, src/components/panel-admin/side-bar/side-bar.jsx, src/utils/firebase/firebaseClient.js
re configurado el ancho de create product
=> Correct style

src/App.jsx, src/components/panel-admin/create-product/create-product.jsx, src/components/panel-admin/create-product/create-product.module.css, src/components/panel-admin/home-admin/home-admin.jsx, src/components/panel-admin/orders/ventasTotales.jsx, src/components/panel-admin/orders/ventasTotales.module.css, src/components/panel-admin/side-bar/side-bar.jsx, src/utils/firebase/firebaseClient.js
Se verica que los estilos no rompan nada
=> Verificando

src/components/panel-admin/user/user.jsx
solución de un problema al escribir la ruta perfil
=> arreglo problema en ruta perfil

src/helper/formatOnlinePurchase.js
corrigiendo el formato de onlinePurchases
=> corrigiendo el formato de onlinePurchases

src/components/detail-component/detail/detail-component.jsx, src/components/detail-component/post-review/post-review.jsx, src/components/detail-component/post-review/post-review.module.css, src/components/detail-component/review-component/review-component.jsx, src/routes/detail/ProductDetail.jsx, src/routes/home/home.jsx, src/utils/firebase/firebaseClient.js
agregando las reviews a el componente
=> agregando las reviews a el componente

src/App.jsx
agreglando el error de la ruta about
=> agreglando el error de la ruta about

src/App.jsx
arreglando el error de rutas en la ruta admin  2
=> arreglando el error de rutas en la ruta admin 2

src/App.jsx, src/components/compras/compras.jsx, src/components/navigation/links-navbar/links-navbar.jsx, src/components/panel-admin/user/user.jsx
agregando componente de compras del usuario
=> componente compras

src/components/navigation/links-navbar/links-navbar.jsx, src/components/payment-gateway/checkout-form/checkout-form.jsx, src/components/payment-gateway/checkout-item/checkout-item.jsx, src/components/payment-gateway/payment-form/payment-form.jsx, src/components/payment-gateway/payment-form/payment-form.module.css, src/main.jsx
Se arregla el componente de confirmacion de pagos es responsive
=> Payment form fixed

src/App.jsx, src/components/compras/compras.jsx, src/components/navigation/links-navbar/links-navbar.jsx, src/components/panel-admin/user/user.jsx, src/components/payment-gateway/checkout-form/checkout-form.jsx, src/components/payment-gateway/checkout-item/checkout-item.jsx, src/components/payment-gateway/payment-form/payment-form.jsx, src/components/payment-gateway/payment-form/payment-form.module.css, src/main.jsx
Actulizacion de confirmacion de pagos y el poder ver las ordenes
=> Actulizacion de confirmacion de pagos y el poder ver las ordenes

src/components/panel-admin/edit-product/edit-product.jsx, src/components/panel-admin/edit-product/edit-product.module.css, src/components/panel-admin/side-bar/side-bar.jsx
arreglo de errores en "Modificar Producto"
elimine "Agregar Producto" del menu lateral del admin
=> arreglo errores en Modificar Producto

src/components/panel-admin/users/users.jsx, src/components/panel-admin/users/users.module.css, src/components/sign-in-form/sign-in-form.jsx, src/utils/firebase/firebaseClient.js
Lista de Clientes con opcion de activar/desactivar usuario
** falta que no permita loguearse si esta desactivado --- estoy trabajando en eso
=> implementacion de Lista de Clientes en admin

src/components/detail-component/detail/detail-component.jsx, src/components/detail-component/post-review/post-review.jsx
=> arreglando los problemas con el los details es funcional

src/components/detail-component/detail/detail-component.jsx, src/components/detail-component/post-review/post-review.jsx, src/components/panel-admin/edit-product/edit-product.jsx, src/components/panel-admin/edit-product/edit-product.module.css, src/components/panel-admin/home-admin/home-admin.jsx, src/components/panel-admin/home-admin/home-admin.module.css, src/components/panel-admin/side-bar/side-bar.jsx, src/components/panel-admin/users/users.jsx, src/components/panel-admin/users/users.module.css, src/components/sign-in-form/sign-in-form.jsx, src/utils/firebase/firebaseClient.js
=> Cambios en la funcionalidad de detail

package-lock.json, package.json, src/components/payment-gateway/payment-form/payment-form.jsx, src/components/payment-gateway/payment-form/payment-form.module.css
Agregado confirmacion de compra
=> confirmacion de compra

src/components/card/card.jsx, src/components/card/rating/rating-preview.jsx, src/components/card/sale/sale.jsx
Solución del problema de renderizado
=> Pago descuento

src/components/card/rating/rating-preview.jsx, src/components/panel-admin/all-products/all-products.jsx, src/components/panel-admin/users/users.jsx
1- Ajuste en tablas de usuarios y productos (admin) para que sean responsive - en pantallas chicas solo se visualizan dos columnas-
2- Agregue funcionalidad para que cuando un producto tenga "stock 0" aparezca como "inactivo" y por lo tanto "No disponible en la Tienda"
=> responsive tablas usuarios y productos en admin

src/components/footer/footer.jsx
=> arreglando la ruta del footer

src/components/panel-admin/all-products/all-products.jsx, src/components/panel-admin/orders/ventasTotales.jsx, src/components/panel-admin/users/users.jsx
Correccion de tablas en admin para responsive
- usuarios
- productos
- ventas (+ventana modal de ventas)
=> correccion responsive tablas en admin: usuarios, productos y ventas

src/components/card/card.jsx, src/components/detail-component/detail/detail-component.jsx, src/components/payment-gateway/checkout-item/checkout-item.jsx
Cuando se intenta seleccionar una cantidad mayor al stock disponible lanza error
=> mensaje cuando la cantidad seleccionada no es acorde al stock

src/components/compras/compras.jsx, src/components/compras/compras.module.css, src/routes/contactForm/contactForm.jsx, src/routes/contactForm/contactForm.module.css
Cambios en perfil y en mis compras
=> errores de diseño en mis compras y en perfil corregidos

src/components/detail-component/detail/detail-component.jsx, src/components/panel-admin/home-admin/home-admin.jsx, src/components/panel-admin/orders/helper.js, src/components/panel-admin/orders/ventasTotales.jsx, src/components/payment-gateway/payment-form/payment-form.jsx, src/utils/firebase/firebaseClient.js
agregue los datos de envio a las ordenes para que se vean del lado del admin, tambien agregue funcion de buscar las ordenes en el admin, y ordenamiento por fecha en las ordenes : quedo arreglado lo de ventas diarias,
=> Data user compras

src/App.jsx, src/components/sign-in-form/sign-in-form.jsx, src/routes/reset-password/reset-password.jsx, src/routes/reset-password/reset.module.css, src/utils/firebase/firebaseClient.js
=> reset de contraseña

_redirects, src/components/payment-gateway/payment-form/payment-form.jsx, src/main.jsx, src/routes/reset-password/reset-password.jsx, src/routes/reset-password/reset.module.css
=> Dando formato eliminado bugs

src/components/pagination/pagination.jsx, src/components/payment-gateway/checkout-item/checkout-item.jsx, src/features/userCredentials/userCredentialsSlice.js, src/routes/user-profile/user-profile.jsx
agregando la funcionalidad de eliminar el perfil
=> agregando la funcionalidad de eliminar el perfil

src/components/panel-admin/user/user.jsx
=> últimos detalles

src/components/pagination/pagination.jsx, src/components/panel-admin/user/user.jsx, src/components/payment-gateway/checkout-item/checkout-item.jsx, src/features/userCredentials/userCredentialsSlice.js, src/routes/user-profile/user-profile.jsx
=> formateandoAdmin

src/components/payment-gateway/payment-form/helperStock.js, src/components/payment-gateway/payment-form/payment-form.jsx, src/utils/firebase/firebaseClient.js
reduciendo el stock de productos
=> reduciendo el stock de productos

src/components/panel-admin/home-admin/home-admin.jsx
te envio la pequeña correcion que no te presentaba las ordenes del dia
=> mando pequeña correccion
